name: Push-to-EC2
# Trigger deployment only on push to main branch
on:
 push:
   branches:
     - main
jobs:
 deploy:
   name: Deploy to EC2 on master branch push
   runs-on: ubuntu-latest
   steps:
      - name: Checkout the code
        uses: actions/checkout@v4      
      
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
         REMOTE_HOST: ${{ secrets.HOST_DNS }}
         REMOTE_USER: ${{ secrets.USERNAME }}
         TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST_DNS }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           sudo apt-get -y update
           sudo apt-get install -y apache2
           sudo systemctl start apache2
           sudo systemctl enable apache2
           #cd /var/www/html/theme/
           #sudo mv * /var/www/html/
      - name: 📂 rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/
          remote_host: ${{ secrets.HOST_DNS }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key:  ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 📂 Set ownership on remote server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Create known_hosts file if it doesn't exist
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          
          # Clear old key from known_hosts
          ssh-keygen -R <3.145.89.117> >> /home/runner/.ssh/known_hosts

          # Run the SSH command
          #ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@<your_ec2_ip_address> \
          #"sudo chown -R ec2-user:apache /var/www/html/ && chmod 777 -R /var/www/html/storage && chmod -R 777 /var/www/html/<your_project_directory>/<your_code_directory>/bootstrap/cache/ && cd /var/www/html/<your_project_directory>/<your_code_directory>/ && sudo npm install -g vite  && npm install && sudo chown -R ec2-user:apache /var/www/html/<your_project_directory>/ && chmod +x /var/www/html/<your_project_directory>/<your_code_directory>/dev_run.sh"          
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}    
          
     
