name: Push-to-EC2
# Trigger deployment only on push to main branch
on:
 push:
   branches: [main]
 pull_request:
    branches: [main]
    
jobs:
 deploy:
   name: Deploy to EC2 on master branch push
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          ref: main
        env:
         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
         REMOTE_HOST: ${{ secrets.HOST_DNS }}
         REMOTE_USER: ${{ secrets.USERNAME }}
         TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST_DNS }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
      
         script: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i key ${username}@${host} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd ..
              cd ..
              cd /var/www/html/ &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main
              ' 
