name: Push-to-EC2
# Trigger deployment only on push to main branch
on:
 push:
   branches:
     - main
jobs:
 deploy:
   name: Deploy to EC2 on master branch push
   runs-on: ubuntu-latest
   steps:
      - name: Checkout the code
        uses: actions/checkout@v4      
      
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
         REMOTE_HOST: ${{ secrets.HOST_DNS }}
         REMOTE_USER: ${{ secrets.USERNAME }}
         TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST_DNS }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           sudo apt-get -y update
           sudo apt-get install -y apache2
           sudo systemctl start apache2
           sudo systemctl enable apache2
           #cd /var/www/html/
           #sudo mv * /var/www/html/
           ssh -o StrictHostKeyChecking=no -i ${{  secrets.EC2_SSH_KEY  }} ec2-3-145-89-117.us-east-2.compute.amazonaws.com 'cd /var/www/html/ && git pull origin main'
     
